CREATE TABLE novaera_participantes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  join_time DATETIME NOT NULL,
  start_time DATETIME NOT NULL
);